#!/usr/bin/env php
<?php
/**
 **
 **
 **
 **/
 
require (__DIR__ . '/vendor/autoload.php'); 

//define ("__ROOT_PATH__", __DIR__);

if (count($argv) > 1)
{
	$achannel = $argv[1];
	$app = new CMP\BackendTest\Launcher ($achannel);
	$app->run();
}

